---
- hosts: all

  sudo: yes

  tasks:

  - name: Write local settings files
    template: src=assets/local_settings.j2 dest={{app_path}}/python/ecep/local_settings.py

  - name: Create logging folders
    file: path=/var/log/ecep/ state=directory owner={{ansible_ssh_user}} mode=0777

  - command: touch {{django_log_file}}

  - file: path={{django_log_file}} state=file owner={{ansible_ssh_user}} mode=0777

  - name: Sync database
    django_manage: command=syncdb app_path={{app_path}}/python/ecep/ virtualenv={{env_path}}
    register: sync_ecep_database

  - name: Load FAQ Data into Django
    command: "{{env_path}}/bin/python {{app_path}}/python/ecep/manage.py loaddata {{item}}"
    when: sync_ecep_database == 'True'
    with_items:
       - faq

  - name: Create static/files files folders
    file: path={{static_path}} state=directory owner={{ansible_ssh_user}}
    file: path={{media_path}} state=directory owner={{ansible_ssh_user}}

  - name: Collect static files
    command: "{{env_path}}/bin/python {{app_path}}/python/ecep/manage.py collectstatic --noinput"

  - name: Copy jenkins testing script
    template: src=assets/run_jenkins_tests.j2 dest={{app_path}}/run_jenkins_tests.sh
    when: django_jenkins == 'True'

  - name: Fix permissions on language files
    file: path={{app_path}}/python/ecep/locale state=directory owner={{ansible_ssh_user}} mode=0777

  - name: Compile messages for i18n
    command: "{{env_path}}/bin/python {{app_path}}/python/ecep/manage.py compilemessages"

  - name: Restart gunicorn
    action: service name=ecep state=restarted
    when: not {{django_jenkins}}